version: 2
sources:
  - name: raw # alias de la table
    schema: gz_raw_data #Nom exact du dataset dans BQ
    description: greenwez raw data source
    tables:
      - name: sales # alias de la table
        identifier: raw_gz_sales #Nom exact de la table dans BQ
        description: sales of greewneez / we have one row per product_id found in each order_id
        # Freshness testing - make sure to fill in the ...
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
           warn_after:
             count: 90
             period: day  
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipping_fee by orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: ads_cost by campaign_key by day
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: bing
        identifier: raw_gz_bing
        description: ads_cost by campaign_key by day
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: criteo
        identifier: raw_gz_criteo
        description: ads_cost by campaign_key by day
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description: ads_cost by campaign_key by day
        columns:
          - name: "(date_date || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null